package TelaAtalhosDeTeclado;


import javax.swing.table.DefaultTableModel;


public class TelaAtalhosDeTeclado extends javax.swing.JFrame {

    DefaultTableModel modelo; //Criação do tipo da tabela da aba "atalhos".
    
    public TelaAtalhosDeTeclado() {
        initComponents();
        this.setExtendedState(HEIGHT); //Localizar "Preferencias" no canto superior esquerdo.
        setarAtalhos(); // Preencher a tabela "modelo" com os atalhos e suas descrições
        
        
    }
    
    public void setarAtalhos(){
        /* Método criado para adicionar todos os atalhos na aba "atalhos"
         * A String "atalho" guarda o valor do atalho
         * A string "desc" guarda a descrição do que o atalho faz
         * Depois o método addRow é usado com esses dois objetos para
         * adicionar uma linha com o atalho e sua descrição.
         */
        
        modelo = (DefaultTableModel) tabela.getModel();
        
         String atalho = "p";
         String desc = "Para adicionar o sinal ^";
         modelo.addRow(new String[]{atalho, desc});
        
         atalho = "d";
         desc = "Para adicionar o sinal ÷";
         modelo.addRow(new String[]{atalho, desc});
         
         atalho = "r";
         desc = "Para adicionar o sinal √";
         modelo.addRow(new String[]{atalho, desc});
         
         atalho = "c";
         desc = "Para acionar o botão CE";
         modelo.addRow(new String[]{atalho, desc});
         
         atalho = "x";
         desc = "Para adicionar o sinal X";
         modelo.addRow(new String[]{atalho, desc});
         
         atalho = "Direcional Esquerdo <-";
         desc = "Remove sempre o último valor digitado";
         modelo.addRow(new String[]{atalho, desc});
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Atalho", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
        }

        jTabbedPane1.addTab("Atalhos", jScrollPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("           Adição ( + ) : Dez Mais Sete                      -> 10 + 7  \n     Subtração ( - ) : Dez Menos Três                   -> 10 - 3    \nMultiplicação ( x ) : Doze Vezes Quatro              -> 12 x 4\n          Divisão ( ÷ ) : Onze Dividido por Três       -> 11 ÷ 3\n   Radiciação (√ ) : Raiz Doze de Um                 -> 12 √ 1\n Potenciação  ( ^ ) : Dez elevado a Dois             -> 10 ^ 2");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Funcionamento Operadores", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
